language: node_js

node_js:
  - 'node'

script:
  - yarn test
  - pushd test/e2e
  - docker-compose run postgres-overlay
  - popd

after_success:
  - 'find ./.nyc_output -type f -name "*.json" | xargs perl -i -pe "s#/usr/src/app#.#g"'
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
